#!/bin/bash
#
#
#
# Start openldapwith mysql
#
# chkconfig: 345 70 30
# description: slapd
# processname: slapd

. /etc/init.d/functions

RETVAL=0
prog="Slapd"
LOCKFILE=/var/lock/subsys/$prog



start() {
        echo -n "Starting $prog: "
        /opt/openldap/servers/slapd/slapd -s 64 -h 'ldap:/// ldapi:///' -f /etc/openldap/slapd.conf 
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch $LOCKFILE
        echo
        return $RETVAL
}

stop() {
        echo -n "Shutting down $prog: "
        pidof slapd | xargs kill -9  
	RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
        echo
        return $RETVAL
}

status() {
        echo -n "Checking $prog status: "
        ps aux | grep slapd
        RETVAL=$?
        return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
	start
        ;;
    *)
        echo "Usage: $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
